name: tes_express_app_new
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_native_splash: ^2.4.4
  go_router: ^14.6.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  http: ^1.3.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.3.1
  dio: ^5.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Thin.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/SF-Pro-Display-Ultralight.ttf
          weight: 100
          style: normal

flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      remove_alpha_ios: true
      image_path: "assets/images/tes_express_logo.png"
      min_sdk_android: 24 
      adaptive_icon_background: "#4A4A4C" 
      adaptive_icon_foreground: "assets/images/tes_express_logo.png"
      

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splasch_icon.png
  android_12: 
    image: assets/images/splasch_icon.png
    color: "#FFFFFF"
    branding: assets/images/branding_image.png
  branding: assets/images/branding_image.png

