name: tes_test_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  go_router: ^14.6.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/fonts/
  fonts:
  - family: SFProDisplay
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: assets/fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: assets/fonts/SF-Pro-Display-Light.otf
        weight: 300
      - asset: assets/fonts/SF-Pro-Display-Thin.otf
        weight: 200
      - asset: assets/fonts/SF-Pro-Display-Black.otf
        weight: 900
      - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        weight: 100
